# jekyll base setting
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["hard_wrap", "tables"]
safe: false
timezone: UTC
lsi: false
baseurl: /

# blog setting
title : "Tavi's Travelog"
author :
  name : tavi
  email : <script type="text/javascript">document.write('<a href="mai' + 'lto:&#114;&#12' + '1;&#111;&#116;&#97;&#107;&#97;&#116;&#111;&#52;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;">&#114;&#12' + '1;&#111;&#116;&#97;&#107;&#97;&#116;&#111;&#52;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;</a>');</script>
  github : ryotakato
  twitter : tavi4444
  facebook : ryota.kato.169

permalink: /:year/:month/:day/:title 


# variable setting
path :
  archive: /archive.html
  categories : /categories.html
  tags : /tags.html
  atom : /atom.xml
